version: "3"
services:
  tmp-user-service:
    build: ./user-service
    container_name: tmp-user-service
    expose:
      - "8000"
    ports:
      - "8000:8000"
    env_file:
      - '.env'
    networks:
      - app-network
  
  tmp-customer-service:
    build: ./customer-service
    container_name: tmp-customer-service
    expose:
      - "8001"
    ports:
      - "8001:8001"
    env_file:
      - '.env'
    depends_on: 
      - 'tmp-user-service'
    networks:
      - app-network
 
  tmp-product-service:
    build: ./product-service
    container_name: tmp-product-service
    expose:
      - "8002"
    ports:
      - "8002:8002"
    env_file:
      - '.env'
    depends_on: 
      - 'tmp-user-service'
    networks:
      - app-network
 
  tmp-order-service:
    build: ./order-service
    container_name: tmp-order-service
    expose:
      - "8003"
    ports:
      - "8003:8003"
    env_file:
      - '.env'
    depends_on: 
      - 'tmp-user-service'
      - 'tmp-customer-service'
      - 'tmp-product-service'
    networks:
      - app-network
 
  tmp-web-app:
    build: ./web-app
    container_name: tmp-portal
    expose:
      - "8005"
    ports:
      - "8005:8005"
    env_file:
      - '.env'
    depends_on:
      - 'tmp-user-service'
      - 'tmp-customer-service'
      - 'tmp-product-service'
      - 'tmp-order-service'
    networks:
      - app-network

networks:
  app-network:
    external: false