version: "2"
services:
  test-product-service:
    build: ../
    container_name: test-product-service
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - SPRING_PROFILES_ACTIVE=test
    expose:
      - "8202"
    ports:
      - "8202:8202"
    networks:
      - curso-automacao_app-network

networks:
  curso-automacao_app-network:
    external: true