pipeline {
    agent any
    stages {
        stage ('Pre-Build') {
            steps {
                sh 'java --version'
            }
        }
        stage ('Build') {
            steps {                        
                sh 'cd web-app && ./mvnw clean package -DskipTests'
            }
        }
        stage ('Unit Test'){
            steps {
            	echo "All tests will run on other projects"
                //sh 'cd web-app && ./mvnw test -Dgroups="unit-tests"'
                //sleep(time:1,unit:"SECONDS") 
            }
        }
        stage ('Deploy to Development Environment'){
            steps {
                sh 'cd web-app/docker'
                sh 'ls -la'
                sh 'cd web-app/docker && docker-compose -p curso-automacao -f docker-compose-dev.yml up --build --force-recreate -d dev-web-app'
                sleep(time:1,unit:"SECONDS") 
            }
        }
        stage ('Integration Test'){
            steps {
            	echo "All tests will run on other projects"
                //sh 'cd web-app && ./mvnw test -Dgroups="integration-tests"'
                //sleep(time:1,unit:"SECONDS") 
            }
        }
        stage ('Deploy to Test Environment'){
            steps {
                sh 'cd web-app/docker'
                sh 'ls -la'
                //sh 'cd web-app/docker && docker-compose -p curso-automacao -f docker-compose-test.yml up --build --force-recreate -d test-web-app'
                //sleep(time:1,unit:"SECONDS") 
            }
        }
        stage ('Acceptance Test'){
            steps {
            	echo "All tests will run on other projects"
               	//sh 'cd web-app && ./mvnw test -Dgroups="acceptance-tests"'
                //sleep(time:1,unit:"SECONDS") 
            }
        }
        stage ('Deploy to Production Environment'){
            steps {
                sh 'cd web-app/docker'
                sh 'ls -la'
                //sh 'cd web-app/docker && docker-compose -p curso-automacao -f docker-compose-prod.yml up --build --force-recreate -d prod-web-app'
                //sleep(time:1,unit:"SECONDS") 
            }
        }
    }   
}