version: "2"
services:
  test-web-app:
    build: ../
    container_name: test-portal
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - SPRING_PROFILES_ACTIVE=test
    expose:
      - "8205"
    ports:
      - "8205:8205"
    networks:
      - curso-automacao_app-network      
      
networks:
  curso-automacao_app-network:
    external: true