version: "2"
services:
  dev-order-service:
    build: ../
    container_name: dev-order-service
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
    expose:
      - "8103"
    ports:
      - "8103:8103"
    networks:
      - curso-automacao_app-network

networks:
  curso-automacao_app-network:
    external: true